CREATE TABLE IF NOT EXISTS tipo_transacao (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
		
CREATE TABLE IF NOT EXISTS transacoes (
	id INT AUTO_INCREMENT PRIMARY KEY,
	descricao VARCHAR(255) NOT NULL,
	valor DECIMAL(10, 2) NOT NULL,
	tipo_transacao_id INT,
	categoria VARCHAR(255) NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (tipo_transacao_id) REFERENCES tipo_transacao(id)
);